import flet as ft

civics_questions = [
    ("What is the supreme law of the land in the United States?", "The Constitution"),
    ("How many branches of government are there in the United States?", "Three (Executive, Legislative, Judicial)"),
    ("Who is known as the 'Father of the Constitution'?", "James Madison"),
    ("What is the minimum voting age in the United States?", "18 years old"),
    ("How many amendments are there in the United States Constitution?", "27 amendments"),
    ("What document declared the American colonies independent from Great Britain?", "The Declaration of Independence"),
    ("Who is the current Chief Justice of the United States Supreme Court?", "John G. Roberts Jr."),
    ("What is the purpose of the Bill of Rights?", "To protect individual rights and freedoms"),
    ("How many senators are there in the U.S. Senate?", "100 senators"),
    ("In what year did the United States declare its independence?", "1776"),
    ("What is the capital of the United States?", "Washington, D.C."),
    ("Who was the first President of the United States?", "George Washington"),
    ("What is the official language of the United States?", "There is no official language at the federal level."),
    ("How many members are there in the U.S. House of Representatives?", "435 members"),
    ("Who is the current Vice President of the United States?", "Kamala Harris"),
    ("What is the term length for a U.S. Senator?", "6 years"),
    ("Which amendment gave women the right to vote?", "19th Amendment"),
    ("What is the economic system of the United States?", "Mixed economy"),
    ("Who wrote the Gettysburg Address?", "Abraham Lincoln"),
    ("What is the nickname of the U.S. flag?", "The Stars and Stripes"),
    ("Who has the power to declare war in the United States?", "Congress"),
    ("What is the highest court in the United States?", "The Supreme Court"),
    ("Which ocean is on the east coast of the United States?", "Atlantic Ocean"),
    ("What is the nickname of the U.S. national anthem?", "The Star-Spangled Banner"),
    ("What are the first ten amendments to the Constitution called?", "The Bill of Rights"),
    ("Who was the main author of the Declaration of Independence?", "Thomas Jefferson"),
    ("Which President is associated with the Emancipation Proclamation?", "Abraham Lincoln"),
    ("What is the electoral college?", "A group of electors chosen to elect the President and Vice President"),
    ("What is the primary responsibility of the Executive Branch?", "To enforce and carry out laws"),
    ("What is the purpose of the Preamble to the U.S. Constitution?", "To introduce and explain the purpose of the Constitution")
]

history_questions = [
    ("Which ancient civilization developed the first system of writing?", "Sumerians"),
    ("Who was the founder of Buddhism?", "Siddhartha Gautama"),
    ("What was the Silk Road?", "A network of trade routes connecting the East and West"),
    ("What empire was ruled by Julius Caesar and Augustus?", "Roman Empire"),
    ("Which Chinese dynasty is known for the construction of the Great Wall?", "Qin Dynasty"),
    ("Who was Mansa Musa and why is he significant?", "Mansa Musa was the ruler of the Mali Empire and known for his pilgrimage to Mecca, showcasing Mali's wealth."),
    ("What was the significance of the Battle of Marathon?", "A decisive Greek victory over the Persians during the Persian Wars"),
    ("Who wrote 'The Prince' and what was its main theme?", "Niccolò Machiavelli; the main theme is political realism and advice for rulers"),
    ("What was the primary motivation for European exploration in the 15th century?", "Desire for new trade routes and resources"),
    ("What was the Columbian Exchange?", "The exchange of goods, ideas, and diseases between the Old World and the New World"),
    ("What was the impact of the Black Death on Europe in the 14th century?", "Significant population decline and social upheaval"),
    ("Who was Zheng He and what was his contribution to Chinese history?", "A Chinese explorer who led seven voyages during the Ming Dynasty, expanding Chinese influence"),
    ("What was the Industrial Revolution and where did it begin?", "A period of economic and technological change; it began in England"),
    ("What was the significance of the Haitian Revolution?", "First successful slave revolt leading to the establishment of the independent state of Haiti"),
    ("Who were the main leaders of the Mexican Revolution?", "Emiliano Zapata and Pancho Villa"),
    ("What was the 'White Man's Burden' and who popularized this concept?", "The idea that Europeans had a moral responsibility to civilize other cultures; popularized by Rudyard Kipling"),
    ("What was the main cause of World War I?", "Assassination of Archduke Franz Ferdinand of Austria-Hungary"),
    ("What was the Treaty of Versailles and how did it impact Germany?", "The peace treaty that ended World War I; it imposed harsh penalties on Germany, contributing to economic and political instability"),
    ("What were the main causes of the Russian Revolution of 1917?", "Social inequality, economic hardship, and the impact of World War I"),
    ("Who were the major leaders of the Allied Powers during World War II?", "Winston Churchill, Franklin D. Roosevelt, Joseph Stalin"),
    ("What was the Holocaust and how did it impact Jewish communities?", "Systematic genocide of six million Jews by the Nazis during World War II; led to profound and lasting effects on Jewish communities worldwide"),
    ("What was the Cold War and what were its main characteristics?", "A geopolitical tension between the United States and the Soviet Union, characterized by ideological and political rivalry"),
    ("What was apartheid and in which country did it occur?", "A system of racial segregation in South Africa"),
    ("What was the Green Revolution and how did it impact agriculture?", "Introduction of new technologies and crop varieties, leading to increased agricultural productivity"),
    ("What were the causes and consequences of the Iranian Revolution in 1979?", "Causes included dissatisfaction with the Shah's regime; consequences included the establishment of an Islamic Republic"),
    ("Who was Nelson Mandela and what role did he play in South Africa's history?", "Anti-apartheid activist and the first black president of South Africa, promoting reconciliation and unity"),
    ("What was the Rwandan Genocide and what were its root causes?", "Ethnic violence resulting in the mass killing of Tutsis by Hutus; root causes included historical tensions and political manipulation"),
    ("What is globalization and how has it affected economies and cultures?", "The increasing interconnectedness of the world; it has led to economic interdependence and cultural exchange"),
    ("What is the significance of the United Nations in global affairs?", "An international organization aimed at maintaining peace and cooperation among nations"),
    ("What is the concept of 'total war' and how did it manifest during the 20th century?", "A conflict involving all aspects of a society; manifested in both World Wars with widespread mobilization and civilian involvement")
]
